### ISSUE TITLE
Hyperbahn lazy relay errors

### ISSUE THREAD

**Issue by Raynos** [uber/hyperbahn#29] opened 2015-10-05 21:37 UTC
```
1.	Cannot read property 'length' of undefined	 	316
2.	Object #<LazyRelayOutReq> has no method 'onTimeout'	 	178
3.	Cannot call method 'cancel' of null	 	4
4.	Object #<LazyRelayInReq> has no method 'onTimeout'         2
```

cc @jcorbin

**Comment by jcorbin** [comment] 2015-10-05 21:53
Working on this in  https://github.com/uber/tchannel-node/pull/37

**Comment by jcorbin** [comment] 2015-10-05 21:54
1. is https://github.com/uber/tchannel-node/commit/6e6f52706f18f368e0ae7b6306d93505c8f7e28f

**Comment by jcorbin** [comment] 2015-10-05 22:16
2. and 4. are https://github.com/uber/tchannel-node/commit/ccb39cd26a1f396aeb9fc756271401922b7479ab

**Comment by jcorbin** [comment] 2015-10-06 01:00
We've decided that 3. is Not A Thing ™, and are chalking it up to state corruption caused by one of the other uncaughts mentioned here.

**Comment by jcorbin** [comment] 2015-10-06 01:36
We've also seen:
```
TypeError: Object #<LazyRelayOutReq> has no method 'emitError'
    at eachOutOp (.../tchannel/connection.js:606:13)
...
```
now fixed in mentioned PR.

**Comment by jcorbin** [comment] 2015-10-06 01:43
Related #31 will be solved separately.

**Closed** 2015-10-12 17:50 UTC
